/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.ashideng.word

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    val template = Template()
    template.generteTemplate()
}
